### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by farshidtz** [linksmart/border-gateway#29]
The readme should contain at least the project description, link to documentation, and instructions for developers/contributors.

ToDo:
- [x] ci badges
- [x] project description
- [x] link to documentation
- [ ] instructions for developers/contributors

**Comment by raphaelahrens** [comment]
See #31, what is missing is the instructions for developers/contributors. Do we have a standard form?

**Comment by farshidtz** [comment]
@raphaelahrens no but something similar to this is a good start: https://github.com/linksmart/historical-datastore/blob/master/README.md
