### ISSUE TITLE
Deprecatoion of Websocket

### ISSUE THREAD

**Issue by raphaelahrens** [linksmart/border-gateway#41]
I think the WebSocket proxy should be deprecated. 
As far as I know we did not use it in any deployment (please correct me if I'm wrong).

We only support connection level authorization, which gives the burden to the WebSocket service to do the rest of the authorization. This then makes the BGW look redundant.

To support better authz rules for WebSocket we need to have an understand what is going over the WebSocket connection. In cases like MQTT over WebSocket this is possible, but not for custom protocols. To support custom protocols we would need to have a modular authz system, where one could write a plugin which retrieves the  authz relevant information from the connection and a description of rules and how to enforce them.

**Comment by farshidtz** [comment]
This was recently added after a feature request by me. I need it to protect [this api](https://github.com/cpswarm/deployment-tool/wiki/Events) which provides events to consumers. There, different resources are queried (subscribed to) using URI query parameters.

I believe the websocket authorization in BGW can be similar to HTTP. This way, we can secure a websocket server, as long as it provides different events under different paths.
